name: insta_king
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.2.0
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  oktoast: ^3.3.2+1
  flutter_riverpod: ^2.4.5
  get_it: ^7.6.4
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.1
  hooks_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  theme_manager: ^2.0.2
  awesome_dialog: ^3.1.0
  lottie: ^2.7.0
  auto_size_text: ^3.0.0
  local_auth: ^2.1.7
  dropdown_button2: ^2.3.9
  anim_search_bar: ^2.0.3
  timezone: ^0.9.2
  rxdart: ^0.27.7
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.0
  onboarding: ^3.1.0
  confetti: ^0.7.0
  text_3d: ^0.0.4
  flutter_staggered_animations: ^1.1.1
  webview_flutter: ^4.7.0
  custom_context_menu: ^0.1.2
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/svgs/
    - shorebird.yaml


  fonts:
    - family: Montesserat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf

