// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Uq-2DLbvkLOoZ04wRRD-PrV91czU1F4',
    appId: '1:249411629199:web:4e46424a409eeafbed80fa',
    messagingSenderId: '249411629199',
    projectId: 'insta-king-mobile',
    authDomain: 'insta-king-mobile.firebaseapp.com',
    storageBucket: 'insta-king-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVAD8O6NXf2Jk9NzV9XUgKkjbHDRjesA',
    appId: '1:249411629199:android:bb1aec11d0a5c1c6ed80fa',
    messagingSenderId: '249411629199',
    projectId: 'insta-king-mobile',
    storageBucket: 'insta-king-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Mbz883GYmkoDCBTLq6jmeGjEeikh3fc',
    appId: '1:249411629199:ios:aa3affb7303f926bed80fa',
    messagingSenderId: '249411629199',
    projectId: 'insta-king-mobile',
    storageBucket: 'insta-king-mobile.appspot.com',
    iosBundleId: 'com.example.instaKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Mbz883GYmkoDCBTLq6jmeGjEeikh3fc',
    appId: '1:249411629199:ios:2f4716c3d8170de2ed80fa',
    messagingSenderId: '249411629199',
    projectId: 'insta-king-mobile',
    storageBucket: 'insta-king-mobile.appspot.com',
    iosBundleId: 'com.example.instaKing.RunnerTests',
  );
}
